# E-Commerce Sales Data Analysis using Python and Pandas

**Objective:** Analyze the provided e-commerce sales dataset using Pandas. The notebook covers data selection, filtering, sorting, `groupby()`, aggregation, sales statistics, and meaningful business observations.

## 1. Import Required Libraries

We use Pandas for data manipulation and analysis.

In [7]:
import pandas as pd
import numpy as np




# Load data into DataFrame
df = pd.read_csv("/content/E_commerece_dataset.csv")

# Convert date column to datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (100, 13)

## 3. Inspect the Dataset

In [ ]:
# Display the first five rows
df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [ ]:
# Display the last five rows
df.tail()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [ ]:
# Dataset shape
print("Rows and columns:", df.shape)

# Column names
print("\nColumns:")
print(df.columns.tolist())

Rows and columns: (100, 13)

Columns:
['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

In [ ]:
# Data types and non-null information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    datetime64[ns]
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(4), object(6)
memory usage: 10.3+ KB

In [ ]:
# Descriptive statistics for numerical columns
df.describe()

,Order_ID,Order_Date,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating
count,100.000000,100,100.000000,100.000000,100.000000,100.000000,100.000000
mean,1050.500000,2026-04-02 03:07:12,2.940000,1647.000000,6.500000,4472.629500,4.322000
min,1001.000000,2026-01-01 00:00:00,1.000000,499.000000,0.000000,449.100000,3.500000
25%,1025.750000,2026-02-23 00:00:00,2.000000,799.000000,0.000000,1948.050000,4.100000
50%,1050.500000,2026-03-29 00:00:00,3.000000,1499.000000,5.000000,3228.300000,4.300000
75%,1075.250000,2026-05-16 00:00:00,4.000000,2499.000000,11.250000,6427.562500,4.700000
max,1100.000000,2026-06-30 00:00:00,5.000000,3499.000000,15.000000,13995.000000,5.000000
std,29.011492,NaN,1.391315,970.054669,6.092718,3324.306691,0.414285

## 4. Basic Data Selection

Select individual columns and multiple columns using Pandas.

In [ ]:
# Select one column
df['Product'].head()

0    Wireless Headphones
1          Running Shoes
2             Power Bank
3    Mechanical Keyboard
4            Smart Watch
Name: Product, dtype: object

In [ ]:
# Select multiple columns
df[['Order_ID', 'Customer', 'Product', 'Total_Sales']].head(10)

   Order_ID      Customer              Product  Total_Sales
0      1001     Kabir Ali  Wireless Headphones      4497.00
1      1002  Aditya Verma        Running Shoes      2799.00
2      1003    Sara Ahmed           Power Bank      2038.30
3      1004     Kabir Ali  Mechanical Keyboard      9496.20
4      1005   Priya Menon          Smart Watch      3134.05
5      1006     Manya Rao        The Alchemist       449.10
6      1007    Alina Shah         Water Bottle      1398.00
7      1008    Aman Kumar               Hoodie      6076.20
8      1009    Aman Kumar      Electric Kettle      4497.00
9      1010    Aman Kumar               Jacket      8996.40

In [ ]:
# Select rows using loc
df.loc[0:4, ['Order_ID', 'City', 'Category', 'Total_Sales']]

   Order_ID       City     Category  Total_Sales
0      1001  Hyderabad  Electronics      4497.00
1      1002      Jammu       Sports      2799.00
2      1003    Chennai  Electronics      2038.30
3      1004    Lucknow  Electronics      9496.20
4      1005      Jammu  Electronics      3134.05

## 5. Filtering Data

In [ ]:
# Orders with sales greater than 5,000
high_sales_orders = df[df['Total_Sales'] > 5000]
high_sales_orders[['Order_ID', 'Customer', 'Product', 'Total_Sales']].head(10)

    Order_ID      Customer              Product  Total_Sales
3       1004     Kabir Ali  Mechanical Keyboard      9496.20
7       1008    Aman Kumar               Hoodie      6076.20
9       1010    Aman Kumar               Jacket      8996.40
10      1011     Rahul Das         Coffee Maker      6998.00
12      1013   Maryam Khan               Jacket     10620.75
13      1014     Dev Patel        Running Shoes      8397.00
16      1017    Sana Malik          Cricket Bat      7497.00
18      1019  Reyansh Jain               Jacket      7497.00
27      1028    Sana Malik  Wireless Headphones      5696.20
28      1029    Sara Ahmed  Wireless Headphones      5696.20

In [ ]:
# Electronics orders
electronics_orders = df[df['Category'] == 'Electronics']
electronics_orders[['Order_ID', 'City', 'Product', 'Total_Sales']].head(10)

    Order_ID        City              Product  Total_Sales
0       1001   Hyderabad  Wireless Headphones      4497.00
2       1003     Chennai           Power Bank      2038.30
3       1004     Lucknow  Mechanical Keyboard      9496.20
4       1005       Jammu          Smart Watch      3134.05
14      1015     Kolkata  Wireless Headphones      2998.00
25      1026  Chandigarh  Wireless Headphones      4497.00
27      1028  Chandigarh  Wireless Headphones      5696.20
28      1029   Hyderabad  Wireless Headphones      5696.20
36      1037        Pune           Power Bank      2038.30
46      1047   Bengaluru       Wireless Mouse      3820.75

In [ ]:
# Orders from the North region with sales above 5,000
north_high_sales = df[(df['Region'] == 'North') & (df['Total_Sales'] > 5000)]
north_high_sales[['Order_ID', 'City', 'Category', 'Product', 'Total_Sales']]

    Order_ID        City        Category              Product  Total_Sales
3       1004     Lucknow     Electronics  Mechanical Keyboard      9496.20
7       1008       Jammu        Clothing               Hoodie      6076.20
12      1013     Lucknow        Clothing               Jacket     10620.75
13      1014      Jaipur          Sports        Running Shoes      8397.00
27      1028  Chandigarh     Electronics  Wireless Headphones      5696.20
38      1039  Chandigarh  Home & Kitchen        Mixer Grinder      5698.10
40      1041       Delhi  Home & Kitchen         Coffee Maker      6648.10
47      1048     Lucknow  Home & Kitchen         Coffee Maker     10497.00
51      1052  Chandigarh     Electronics  Mechanical Keyboard      9496.20
65      1066      Jaipur     Electronics          Smart Watch      5938.20
69      1070       Delhi        Clothing               Jacket      9996.00
79      1080       Delhi        Clothing               Jacket      9996.00
89      1090     Lucknow          Sports          Cricket Bat     12495.00

## 6. Sorting Operations

In [ ]:
# Top 10 orders by total sales
top_orders = df.sort_values('Total_Sales', ascending=False).head(10)
top_orders[['Order_ID', 'Customer', 'City', 'Product', 'Total_Sales']]

    Order_ID      Customer        City              Product  Total_Sales
48      1049  Ishita Gupta      Mumbai        Running Shoes     13995.00
52      1053  Ananya Singh   Hyderabad        Running Shoes     13295.25
84      1085    Sana Malik   Hyderabad         Coffee Maker     12596.40
89      1090  Aditya Verma     Lucknow          Cricket Bat     12495.00
12      1013   Maryam Khan     Lucknow               Jacket     10620.75
47      1048    Sara Ahmed     Lucknow         Coffee Maker     10497.00
69      1070  Aditya Verma       Delhi               Jacket      9996.00
79      1080  Aditya Verma       Delhi               Jacket      9996.00
51      1052   Rohan Mehta  Chandigarh  Mechanical Keyboard      9496.20
3       1004     Kabir Ali     Lucknow  Mechanical Keyboard      9496.20

In [ ]:
# Lowest 10 orders by total sales
lowest_orders = df.sort_values('Total_Sales', ascending=True).head(10)
lowest_orders[['Order_ID', 'Customer', 'Product', 'Total_Sales']]

    Order_ID      Customer                  Product  Total_Sales
5       1006     Manya Rao            The Alchemist       449.10
62      1063    Aman Kumar            The Alchemist       449.10
73      1074    Alina Shah            Atomic Habits       539.10
96      1097    Arjun Nair                  T-Shirt       679.15
60      1061    Alina Shah       Python Programming       711.55
82      1083   Priya Menon                 Football       759.05
30      1031   Rohan Mehta                 Yoga Mat       764.15
42      1043     Kabir Ali                  T-Shirt       799.00
20      1021  Reyansh Jain                 Yoga Mat       809.10
77      1078   Maryam Khan  Machine Learning Basics       899.10

## 7. Overall Sales Statistics

In [ ]:
total_sales = df['Total_Sales'].sum()
average_sales = df['Total_Sales'].mean()
highest_sales = df['Total_Sales'].max()
lowest_sales = df['Total_Sales'].min()
total_quantity = df['Quantity'].sum()
number_of_orders = df['Order_ID'].nunique()

print(f"Total Sales       : ₹{total_sales:,.2f}")
print(f"Average Sales     : ₹{average_sales:,.2f}")
print(f"Highest Sale      : ₹{highest_sales:,.2f}")
print(f"Lowest Sale       : ₹{lowest_sales:,.2f}")
print(f"Total Quantity    : {total_quantity:,}")
print(f"Number of Orders  : {number_of_orders:,}")

Total Sales       : ₹447,262.95
Average Sales     : ₹4,472.63
Highest Sale      : ₹13,995.00
Lowest Sale       : ₹449.10
Total Quantity    : 294
Number of Orders  : 100

## 8. Category-wise Analysis

Use `groupby()` and aggregation to compare categories.

In [ ]:
category_analysis = df.groupby('Category').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Total_Quantity=('Quantity', 'sum'),
    Number_of_Orders=('Order_ID', 'nunique'),
    Average_Rating=('Rating', 'mean')
).sort_values('Total_Sales', ascending=False)

category_analysis

,Total_Sales,Average_Sales,Total_Quantity,Number_of_Orders,Average_Rating
Category,,,,,
Sports,136026.45,5441.058000,79,25,4.400000
Home & Kitchen,113329.90,5396.661905,59,21,4.300000
Electronics,92086.00,4846.631579,57,19,4.236842
Clothing,69028.20,4930.585714,39,14,4.292857
Books,36792.40,1752.019048,60,21,4.347619

## 9. City-wise Analysis

In [ ]:
city_analysis = df.groupby('City').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Total_Quantity=('Quantity', 'sum'),
    Number_of_Orders=('Order_ID', 'nunique')
).sort_values('Total_Sales', ascending=False)

city_analysis

             Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
City
Hyderabad       59076.45    8439.492857              25                 7
Chennai         47493.20    4749.320000              29                10
Lucknow         46194.65    7699.108333              22                 6
Pune            41908.55    4190.855000              34                10
Mumbai          41457.80    5182.225000              23                 8
Kochi           37257.50    4139.722222              29                 9
Chandigarh      34539.65    4317.456250              22                 8
Delhi           30882.80    5147.133333              18                 6
Jaipur          25534.00    3647.714286              17                 7
Kolkata         20169.00    2881.285714              24                 7
Jammu           16059.75    2676.625000              11                 6
Ahmedabad       14788.70    2464.783333              12                 6
Bengaluru       13524.30    3381.075000              14                 4
Srinagar        11778.60    2355.720000              12                 5
Bhubaneswar      6598.00    6598.000000               2                 1

## 10. Product-wise Analysis

In [ ]:
product_analysis = df.groupby('Product').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Total_Quantity=('Quantity', 'sum'),
    Number_of_Orders=('Order_ID', 'nunique'),
    Average_Rating=('Rating', 'mean')
).sort_values('Total_Sales', ascending=False)

product_analysis

,Total_Sales,Average_Sales,Total_Quantity,Number_of_Orders,Average_Rating
Product,,,,,
Coffee Maker,51610.25,7372.892857,16,7,4.514286
Jacket,47106.15,9421.230000,20,5,4.520000
Cricket Bat,41483.40,8296.680000,18,5,4.220000
Running Shoes,41285.25,8257.050000,15,5,4.240000
Wireless Headphones,33877.40,4839.628571,23,7,4.157143
Dumbbell Set,30184.90,6036.980000,16,5,4.780000
Mechanical Keyboard,26489.40,8829.800000,11,3,3.933333
Electric Kettle,26382.40,5276.480000,19,5,4.160000
Mixer Grinder,25341.55,6335.387500,9,4,4.100000
Smart Watch,15670.25,5223.416667,5,3,4.366667
Yoga Mat,12765.80,2127.633333,16,6,4.350000
Atomic Habits,11590.65,1931.775000,21,6,4.450000
Football,10307.10,2576.775000,14,4,4.425000
Water Bottle,9995.70,1999.140000,15,5,4.300000
Wireless Mouse,9574.35,3191.450000,12,3,4.166667
T-Shirt,7790.25,1558.050000,10,5,4.080000
Hoodie,7675.20,3837.600000,5,2,3.900000
Python Programming,7527.45,1881.862500,11,4,4.575000
The Alchemist,7485.00,1247.500000,17,6,4.133333
Power Bank,6474.60,2158.200000,6,3,4.666667
Jeans,6456.60,3228.300000,4,2,4.650000
Machine Learning Basics,5694.30,1423.575000,6,4,4.175000
Data Science Handbook,4495.00,4495.000000,5,1,4.800000

In [ ]:
# Top 5 products by total sales
product_analysis.head(5)

,Total_Sales,Average_Sales,Total_Quantity,Number_of_Orders,Average_Rating
Product,,,,,
Coffee Maker,51610.25,7372.892857,16,7,4.514286
Jacket,47106.15,9421.230000,20,5,4.520000
Cricket Bat,41483.40,8296.680000,18,5,4.220000
Running Shoes,41285.25,8257.050000,15,5,4.240000
Wireless Headphones,33877.40,4839.628571,23,7,4.157143

## 11. Payment Method Analysis

In [ ]:
payment_analysis = df.groupby('Payment_Method').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Number_of_Orders=('Order_ID', 'nunique')
).sort_values('Total_Sales', ascending=False)

payment_analysis

                  Total_Sales  Average_Sales  Number_of_Orders
Payment_Method
Credit Card         106540.25    4842.738636                22
Debit Card           98064.90    4903.245000                20
Net Banking          96371.25    5668.897059                17
UPI                  96163.25    3698.586538                26
Cash on Delivery     50123.30    3341.553333                15

## 12. Region-wise Analysis

In [ ]:
region_analysis = df.groupby('Region').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Total_Quantity=('Quantity', 'sum'),
    Number_of_Orders=('Order_ID', 'nunique')
).sort_values('Total_Sales', ascending=False)

region_analysis

        Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
Region
North     164989.45    4341.827632             102                38
South     157351.45    5245.048333              97                30
West       98155.05    4089.793750              69                24
East       26767.00    3345.875000              26                 8

## 13. Identify Top-Performing Orders and Products

In [ ]:
# Highest-selling order
highest_order = df.loc[df['Total_Sales'].idxmax()]
highest_order[['Order_ID', 'Customer', 'City', 'Product', 'Quantity', 'Total_Sales']]

Order_ID                1049
Customer        Ishita Gupta
City                  Mumbai
Product        Running Shoes
Quantity                   5
Total_Sales          13995.0
Name: 48, dtype: object

In [ ]:
# Lowest-selling order
lowest_order = df.loc[df['Total_Sales'].idxmin()]
lowest_order[['Order_ID', 'Customer', 'City', 'Product', 'Quantity', 'Total_Sales']]

Order_ID                1006
Customer           Manya Rao
City                   Kochi
Product        The Alchemist
Quantity                   1
Total_Sales            449.1
Name: 5, dtype: object

In [ ]:
# Products with the highest quantity sold
top_quantity_products = (
    df.groupby('Product')['Quantity']
      .sum()
      .sort_values(ascending=False)
      .head(5)
)
top_quantity_products

Product
Wireless Headphones    23
Atomic Habits          21
Jacket                 20
Electric Kettle        19
Cricket Bat            18
Name: Quantity, dtype: int64

## 14. Orders with High Ratings

In [ ]:
# Orders with a rating of 4.8 or higher
high_rated_orders = df[df['Rating'] >= 4.8].sort_values('Rating', ascending=False)
high_rated_orders[['Order_ID', 'Customer', 'Product', 'Rating', 'Total_Sales']].head(15)

    Order_ID      Customer                Product  Rating  Total_Sales
24      1025   Rohan Mehta               Football     5.0      3995.00
37      1038  Aditya Verma           Dumbbell Set     5.0      9495.25
35      1036   Rohan Mehta               Yoga Mat     5.0      1798.00
47      1048    Sara Ahmed           Coffee Maker     5.0     10497.00
60      1061    Alina Shah     Python Programming     5.0       711.55
59      1060   Karan Joshi           Dumbbell Set     5.0      5397.30
55      1056   Rohan Mehta           Dumbbell Set     5.0      3798.10
90      1091   Hiba Sheikh          Atomic Habits     5.0      2995.00
73      1074    Alina Shah          Atomic Habits     5.0       539.10
12      1013   Maryam Khan                 Jacket     4.8     10620.75
14      1015    Sana Malik    Wireless Headphones     4.8      2998.00
36      1037     Zoya Khan             Power Bank     4.8      2038.30
62      1063    Aman Kumar          The Alchemist     4.8       449.10
85      1086    Arjun Nair                  Jeans     4.8      3228.30
99      1100     Kabir Ali  Data Science Handbook     4.8      4495.00

## 15. Discount Analysis

In [ ]:
discount_analysis = df.groupby('Discount_Percent').agg(
    Total_Sales=('Total_Sales', 'sum'),
    Average_Sales=('Total_Sales', 'mean'),
    Number_of_Orders=('Order_ID', 'nunique')
).sort_values('Total_Sales', ascending=False)

discount_analysis

                  Total_Sales  Average_Sales  Number_of_Orders
Discount_Percent
0                   182590.00       4805.000                38
5                   107913.35       5679.650                19
15                   90203.70       3608.148                25
10                   66555.90       3697.550                18

## 16. Meaningful Observations

The following cells automatically generate observations from the dataset, so the notebook remains accurate even if the CSV values are changed.

In [ ]:
top_category = category_analysis['Total_Sales'].idxmax()
top_category_sales = category_analysis.loc[top_category, 'Total_Sales']

top_city = city_analysis['Total_Sales'].idxmax()
top_city_sales = city_analysis.loc[top_city, 'Total_Sales']

top_product = product_analysis['Total_Sales'].idxmax()
top_product_sales = product_analysis.loc[top_product, 'Total_Sales']

top_payment = payment_analysis['Total_Sales'].idxmax()
top_payment_sales = payment_analysis.loc[top_payment, 'Total_Sales']

top_region = region_analysis['Total_Sales'].idxmax()
top_region_sales = region_analysis.loc[top_region, 'Total_Sales']

print("Key Observations")
print("-" * 60)
print(f"1. {top_category} is the highest-selling category with total sales of ₹{top_category_sales:,.2f}.")
print(f"2. {top_city} has the highest total sales among cities, with ₹{top_city_sales:,.2f}.")
print(f"3. {top_product} is the top-performing product by total sales, generating ₹{top_product_sales:,.2f}.")
print(f"4. {top_payment} is the payment method associated with the highest total sales, at ₹{top_payment_sales:,.2f}.")
print(f"5. {top_region} is the strongest region by total sales, contributing ₹{top_region_sales:,.2f}.")
print(f"6. The dataset contains {number_of_orders} orders and {total_quantity:,} units sold.")
print(f"7. The average order sales value is ₹{average_sales:,.2f}.")

Key Observations
------------------------------------------------------------
1. Sports is the highest-selling category with total sales of ₹136,026.45.
2. Hyderabad has the highest total sales among cities, with ₹59,076.45.
3. Coffee Maker is the top-performing product by total sales, generating ₹51,610.25.
4. Credit Card is the payment method associated with the highest total sales, at ₹106,540.25.
5. North is the strongest region by total sales, contributing ₹164,989.45.
6. The dataset contains 100 orders and 294 units sold.
7. The average order sales value is ₹4,472.63.

## 17. Conclusion

This analysis demonstrates how Python and Pandas can be used to examine an e-commerce dataset. We used column selection, row filtering, sorting, `groupby()`, and aggregation functions such as `sum()`, `mean()`, `max()`, `min()`, and `nunique()`. The analysis also identified high-value orders, top-performing products and categories, city and region performance, and the contribution of different payment methods.

The generated observations can help a business understand sales performance and identify areas that deserve further investigation.