In [10]:
from google.colab import files
upload= files.upload()

Saving Flight_Operations_Dataset.csv to Flight_Operations_Dataset (1).csv

 1.**Load Dataset and Required libraries**

In [13]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/Flight_Operations_Dataset (1).csv")

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

2. **Understaning Data**

In [22]:
df.head()  ## Returns the first 5 rows of dataset
df.tail() ## returns the kast 5 rows of dataset
df.info()
df.describe()
df.info()
df.columns
df.isnull().sum()
df.shape
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    object
 1   Flight_Date             180 non-null    object
 2   Airline                 180 non-null    object
 3   Origin                  180 non-null    object
 4   Destination             180 non-null    object
 5   Aircraft                180 non-null    object
 6   Travel_Class            180 non-null    object
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           180 non-null    float64
 11  Flight_Status           180 non-null    object
 12  Weather                 180 non-null    object
 13  Booking_Channel         180 non-null    object
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    object
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), object(11)
memory usage: 24.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    object
 1   Flight_Date             180 non-null    object
 2   Airline                 180 non-null    object
 3   Origin                  180 non-null    object
 4   Destination             180 non-null    object
 5   Aircraft                180 non-null    object
 6   Travel_Class            180 non-null    object
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           180 non-null    float64
 11  Flight_Status           180 non-null    object
 12  Weather                 180 non-null    object
 13  Booking_Channel         180 non-null    object
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    object
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), object(11)
memory usage: 24.0+ KB

np.int64(0)

**3.Data Cleaning**

In [23]:
df.drop_duplicates(inplace=True)

df.isnull().sum()

Flight_ID                 0
Flight_Date               0
Airline                   0
Origin                    0
Destination               0
Aircraft                  0
Travel_Class              0
Passengers                0
Seat_Capacity             0
Average_Ticket_Price      0
Delay_Minutes             0
Flight_Status             0
Weather                   0
Booking_Channel           0
Avg_Baggage_Kg            0
Meal_Preference           0
Passenger_Satisfaction    0
dtype: int64

**4.**Data** Selection**

In [30]:
df[['Airline','Flight_ID']].head()
df.loc[:,['Flight_ID','Airline']]
df.iloc[:10]

    Flight_ID    Airline
0      FL0001   SpiceJet
1      FL0002  Akasa Air
2      FL0003  Air India
3      FL0004  Akasa Air
4      FL0005  Air India
..        ...        ...
175    FL0176     IndiGo
176    FL0177    Vistara
177    FL0178     IndiGo
178    FL0179    Vistara
179    FL0180  Akasa Air

[180 rows x 2 columns]

**5.Data Filtering**

In [39]:
df[df['Delay_Minutes'] > 30]

df[df['Flight_Status'] == 'Delayed']

df[(df['Delay_Minutes'] > 30) & (df['Flight_Status'] == 'Delayed')]

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
5,FL0006,2026-05-20,Akasa Air,Kochi,Delhi,Airbus A319,Economy,123,220,5636,35.0,Delayed,Cloudy,Travel Agency,13,Vegetarian,2
8,FL0009,2026-01-25,Akasa Air,Delhi,Chennai,Airbus A320,Economy,82,210,5893,75.0,Delayed,Cloudy,Mobile App,8,Vegetarian,4
21,FL0022,2026-02-01,Vistara,Kochi,Delhi,Airbus A321,Economy,126,220,5887,75.0,Delayed,Clear,Airline Website,10,Vegetarian,2
26,FL0027,2026-02-10,SpiceJet,Bengaluru,Hyderabad,Airbus A319,Economy,169,180,3973,110.0,Delayed,Clear,Mobile App,7,Vegan,4
29,FL0030,2026-04-10,SpiceJet,Delhi,Srinagar,Airbus A321,Economy,200,210,2716,75.0,Delayed,Storm,Airline Website,10,Vegan,3
30,FL0031,2026-01-08,Vistara,Delhi,Srinagar,Airbus A321,Premium Economy,209,180,9962,50.0,Delayed,Cloudy,Mobile App,9,Vegetarian,4
32,FL0033,2026-04-27,Akasa Air,Ahmedabad,Bengaluru,Boeing 737,Business,66,180,17625,35.0,Delayed,Cloudy,Mobile App,15,No Meal,4
42,FL0043,2026-06-19,Vistara,Delhi,Chennai,Airbus A319,Economy,64,220,4029,50.0,Delayed,Clear,Mobile App,5,No Meal,3
43,FL0044,2026-04-20,Air India Express,Bengaluru,Hyderabad,Airbus A319,Economy,176,186,3075,35.0,Delayed,Storm,Travel Agency,16,No Meal,3
44,FL0045,2026-06-05,SpiceJet,Delhi,Srinagar,Airbus A320,Economy,81,186,3975,35.0,Delayed,Clear,Travel Agency,14,Non-Vegetarian,3
50,FL0051,2026-05-03,Air India,Delhi,Mumbai,Airbus A321,Economy,135,210,5129,110.0,Delayed,Rain,Online Travel Portal,17,Vegetarian,4
52,FL0053,2026-05-16,Akasa Air,Mumbai,Bengaluru,Airbus A319,Business,72,210,21499,35.0,Delayed,Clear,Mobile App,15,Non-Vegetarian,2
54,FL0055,2026-04-30,IndiGo,Delhi,Chennai,Airbus A319,Economy,106,220,5432,50.0,Delayed,Storm,Mobile App,19,Non-Vegetarian,2
57,FL0058,2026-04-14,IndiGo,Hyderabad,Kolkata,Boeing 737,Premium Economy,151,210,6834,110.0,Delayed,Cloudy,Travel Agency,16,Vegetarian,4
80,FL0081,2026-04-03,SpiceJet,Delhi,Mumbai,Airbus A320,Economy,199,180,2378,50.0,Delayed,Rain,Online Travel Portal,13,No Meal,4
82,FL0083,2026-04-18,Air India Express,Lucknow,Delhi,Airbus A319,Economy,71,180,2484,110.0,Delayed,Cloudy,Online Travel Portal,22,Vegetarian,4
84,FL0085,2026-05-03,Air India,Lucknow,Delhi,Airbus A319,Economy,45,189,3299,35.0,Delayed,Rain,Online Travel Portal,21,Non-Vegetarian,3
97,FL0098,2026-01-12,SpiceJet,Ahmedabad,Bengaluru,Airbus A319,Economy,131,180,6466,35.0,Delayed,Rain,Online Travel Portal,7,Vegetarian,4
98,FL0099,2026-01-15,Air India,Mumbai,Bengaluru,Boeing 737,Economy,108,189,3588,35.0,Delayed,Rain,Airline Website,14,Non-Vegetarian,4
100,FL0101,2026-05-24,IndiGo,Jaipur,Mumbai,Boeing 737,Economy,62,180,2552,50.0,Delayed,Cloudy,Airline Website,5,No Meal,2
104,FL0105,2026-03-21,Vistara,Delhi,Mumbai,Boeing 737,Economy,158,180,3694,50.0,Delayed,Storm,Mobile App,6,Vegetarian,3
105,FL0106,2026-04-23,IndiGo,Srinagar,Delhi,Boeing 737,Economy,83,220,3471,50.0,Delayed,Fog,Mobile App,23,Non-Vegetarian,3
107,FL0108,2026-05-30,IndiGo,Lucknow,Delhi,Airbus A319,Premium Economy,198,180,10551,75.0,Delayed,Rain,Travel Agency,13,Vegan,2
128,FL0129,2026-01-04,SpiceJet,Lucknow,Delhi,Boeing 737,Premium Economy,67,210,5657,110.0,Delayed,Cloudy,Online Travel Portal,21,Non-Vegetarian,2
131,FL0132,2026-02-04,Air India,Hyderabad,Kolkata,Airbus A321,Economy,61,220,3483,75.0,Delayed,Clear,Mobile App,18,No Meal,5
135,FL0136,2026-03-16,Vistara,Mumbai,Bengaluru,Boeing 737,Economy,150,180,4587,35.0,Delayed,Clear,Airline Website,19,Vegan,4
136,FL0137,2026-03-14,Vistara,Mumbai,Bengaluru,Airbus A319,Economy,73,186,1949,35.0,Delayed,Rain,Airline Website,22,Non-Vegetarian,5
146,FL0147,2026-02-18,IndiGo,Mumbai,Kolkata,Airbus A319,Premium Economy,115,210,9106,110.0,Delayed,Rain,Online Travel Portal,19,Vegetarian,5
156,FL0157,2026-04-25,Akasa Air,Delhi,Srinagar,Boeing 737,Economy,120,186,2188,35.0,Delayed,Storm,Mobile App,14,Non-Vegetarian,2
157,FL0158,2026-02-24,Vistara,Mumbai,Kolkata,Boeing 737,Economy,176,186,3479,75.0,Delayed,Fog,Travel Agency,14,Vegetarian,4
159,FL0160,2026-06-23,Vistara,Lucknow,Delhi,Airbus A321,Economy,91,210,5443,75.0,Delayed,Storm,Airline Website,10,No Meal,2
161,FL0162,2026-01-18,Air India,Hyderabad,Kolkata,Airbus A321,Economy,128,189,5263,110.0,Delayed,Rain,Mobile App,6,Non-Vegetarian,3
168,FL0169,2026-02-10,IndiGo,Delhi,Chennai,Airbus A320,Economy,152,220,4051,35.0,Delayed,Clear,Online Travel Portal,10,No Meal,2
169,FL0170,2026-06-25,IndiGo,Mumbai,Kolkata,Airbus A319,Economy,130,180,3938,110.0,Delayed,Rain,Online Travel Portal,17,No Meal,4
172,FL0173,2026-06-02,SpiceJet,Srinagar,Delhi,Airbus A319,Economy,143,189,6817,75.0,Delayed,Storm,Mobile App,20,No Meal,2
173,FL0174,2026-04-27,Vistara,Hyderabad,Kolkata,Airbus A319,Economy,93,189,3392,50.0,Delayed,Fog,Airline Website,10,No Meal,3
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

In [41]:
df.sort_values(by='Delay_Minutes', ascending=False)

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
50,FL0051,2026-05-03,Air India,Delhi,Mumbai,Airbus A321,Economy,135,210,5129,110.0,Delayed,Rain,Online Travel Portal,17,Vegetarian,4
26,FL0027,2026-02-10,SpiceJet,Bengaluru,Hyderabad,Airbus A319,Economy,169,180,3973,110.0,Delayed,Clear,Mobile App,7,Vegan,4
82,FL0083,2026-04-18,Air India Express,Lucknow,Delhi,Airbus A319,Economy,71,180,2484,110.0,Delayed,Cloudy,Online Travel Portal,22,Vegetarian,4
57,FL0058,2026-04-14,IndiGo,Hyderabad,Kolkata,Boeing 737,Premium Economy,151,210,6834,110.0,Delayed,Cloudy,Travel Agency,16,Vegetarian,4
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,FL0168,2026-05-01,Air India,Delhi,Mumbai,Airbus A319,Economy,47,220,6479,0.0,On Time,Cloudy,Mobile App,18,Vegan,4
166,FL0167,2026-06-15,SpiceJet,Ahmedabad,Bengaluru,Airbus A321,Economy,148,180,6593,0.0,On Time,Rain,Online Travel Portal,15,Non-Vegetarian,5
165,FL0166,2026-05-23,Akasa Air,Kochi,Delhi,Airbus A320,Economy,108,210,2314,0.0,On Time,Fog,Online Travel Portal,6,Vegan,2
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
174,FL0175,2026-04-23,Akasa Air,Bengaluru,Kochi,Airbus A321,Economy,116,180,5883,0.0,On Time,Cloudy,Online Travel Portal,14,Non-Vegetarian,5

In [43]:
df.groupby('Airline').agg({
    'Delay_Minutes':['mean','max','min'],
    'Flight_ID':'count'
})

                  Delay_Minutes             Flight_ID
                           mean    max  min     count
Airline
Air India             20.375000  110.0  0.0        24
Air India Express     11.291667  110.0  0.0        24
Akasa Air             14.322581   75.0  0.0        31
IndiGo                25.031250  110.0  0.0        32
SpiceJet              22.625000  110.0  0.0        32
Vistara               19.648649   75.0  0.0        37

In [48]:
import numpy as np
df["Delay_category"]= np.where(df["Delay_Minutes"]>30,'high delay','low delay')
df.head()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction,Delay_category
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3,high delay
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5,low delay
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2,low delay
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2,high delay
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5,low delay

In [52]:
print("===== FLIGHT OPERATIONS OBSERVATIONS =====\n")

# 1
print("1. Dataset size:")
print(f"The dataset contains {len(df)} flights and {len(df.columns)} columns.\n")

# 2
airline_counts = df['Airline'].value_counts()
print("2. Airline with most flights:")
print(f"{airline_counts.index[0]} operates the highest number of flights "
      f"({airline_counts.iloc[0]} flights).\n")

# 3
avg_delay = df.groupby('Airline')['Delay_Minutes'].mean().sort_values(ascending=False)
print("3. Highest average delay:")
print(f"{avg_delay.index[0]} has the highest average delay "
      f"of {avg_delay.iloc[0]:.2f} minutes.\n")

# 4
print("4. Maximum delay:")
print(f"The maximum recorded delay is {df['Delay_Minutes'].max()} minutes.\n")

# 5
delayed = (df['Flight_Status'] == 'Delayed').sum()
print("5. Delayed flights:")
print(f"There are {delayed} delayed flights in the dataset.\n")

# 6
percentage = (delayed / len(df)) * 100
print("6. Percentage of delayed flights:")
print(f"{percentage:.2f}% of flights were delayed.\n")


# 7
destination_counts = df['Destination'].value_counts()
print("8. Busiest destination airport:")
print(f"{destination_counts.index[0]} receives the highest number of flights "
      f"({destination_counts.iloc[0]} flights).")

===== FLIGHT OPERATIONS OBSERVATIONS =====

1. Dataset size:
The dataset contains 180 flights and 18 columns.

2. Airline with most flights:
Vistara operates the highest number of flights (37 flights).

3. Highest average delay:
IndiGo has the highest average delay of 25.03 minutes.

4. Maximum delay:
The maximum recorded delay is 110.0 minutes.

5. Delayed flights:
There are 59 delayed flights in the dataset.

6. Percentage of delayed flights:
32.78% of flights were delayed.

8. Busiest destination airport:
Delhi receives the highest number of flights (51 flights).